export const FIELD_LABELS_AR: Record<string, string> = {
  avgPrice: "متوسط السعر",
  minPrice: "أقل سعر",
  maxPrice: "أعلى سعر",
  changeRateDaialy: "التغير اليومي",
  changeRatePercentDaialy: "نسبة التغير اليومي",
  minPriceWithinYear: "أقل سعر خلال سنة",
  maxPriceWithinYear: "أعلى سعر خلال سنة",
  minWithinYearDate: "تاريخ أقل سعر سنوي",
  maxWithinYearDate: "تاريخ أعلى سعر سنوي",
  currency: "العملة",
  unit: "الوحدة",
  insertionDate: "تاريخ الإدراج",
  minSubIndicatorName: "اسم الحد الأدنى",
  minSubIndicatorPrice: "سعر الحد الأدنى",
  maxSubIndicatorName: "اسم الحد الأقصى",
  maxSubIndicatorPrice: "سعر الحد الأقصى",
  govMin: "حد أدنى حكومي",
  govMax: "حد أقصى حكومي",
  groupName: "التصنيف العام",
  marketScope: "نطاق السوق",
  indicatorId: "معرف المؤشر",
  mainIndicatorId: "المعرف الرئيسي",
  generalIndicatorId: "معرف المجموعة",
  generalIndicator: "اسم المجموعة",
  indicatorName: "اسم المؤشر",
  indictorName: "اسم المؤشر",
  photo: "الصورة",
};

export const toArabicLabel = (key: string) => FIELD_LABELS_AR[key] ?? key;
